### ISSUE TITLE
Improve debuging section

### ISSUE THREAD

**Issue by SergioGasquez** [esp-rs/book#105]
```[tasklist]
### Tasks
- [ ] Document how to install GDB/openOCD, see https://github.com/esp-rs/espup/issues/257#issuecomment-1564017493
- [x] Improve current sections
- [x] The "Debugging in Visual Studio Code" section should be updated to reflect all supported chips
- [x] note that esp8266 is not supported via openocd-esp32
- [x] Explain the differences between openOCD, VsCode and probe-rs
```

**Comment by SergioGasquez** [comment]
Closed via https://github.com/esp-rs/book/pull/128

**Comment by lure23** [comment]
I'm still confused about how to install OpenOCD - in my case for ESP32-C3 development.

The #128 changelog suggests installing https://github.com/espressif/binutils-gdb 

```
GDB with all the Espressif products supported can be obtained in [`espressif/binutils-gdb`][binutils-repo].
Once installed, it's as simple as running `openocd` with the correct arguments. For chips with the built-in  [`USB-JTAG-SERIAL` peripheral][usb-jtag-serial], there is normally a config file that will work out of the box, for example on the ESP32-C3:
```

The releases of `binutils-gdb` don't provide an `openocd` binary. What are the packages I should install - and how - to get suggested command `openocd -f board/esp32c3-builtin.cfg` runnable (on Linux)?

I presume this part was left somewhat undone. The first checkbox of this issue (closed as duplicate) remains unchecked.

cc @SergioGasquez

**Comment by SergioGasquez** [comment]
> I'm still confused about how to install OpenOCD - in my case for ESP32-C3 development.

OpenOCD comes with the ESP-IDF installation: https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/get-started/index.html#installation.  From the docs:

> If you have already set up ESP-IDF with CMake build system according to the [Getting Started Guide](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/get-started/index.html), then OpenOCD is already installed. After [setting up the environment](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/get-started/linux-macos-setup.html#get-started-set-up-env) in your terminal, you should be able to run OpenOCD. Check this by executing the following command:

**Comment by lure23** [comment]
Thanks, got it.
